/**
 * Tests for `src/agent/opencode/hooks.ts` — Mirrors Go
 * `entire-cli/cmd/entire/cli/agent/opencode/hooks.go` + `hooks_test.go`.
 *
 * **Story-side rebrand checklist** (Go literals → Story literals):
 * - Plugin file name: `entire.ts` → `story.ts`
 * - Production CMD constant: `'entire'` → `'story'`
 * - LocalDev CMD: `go run "$(git rev-parse --show-toplevel)"/cmd/entire/main.go`
 *   → `bun run "$(git rev-parse --show-toplevel)"/src/cli.ts`
 * - Marker comment: `Auto-generated by \`entire enable...\`` → `\`story enable...\``
 *
 * Covers:
 * - Fresh install: writes plugin file to .opencode/plugins/story.ts (Go: TestInstallHooks_FreshInstall)
 * - LocalDev install: file contains 'bun run' (Go: TestInstallHooks_LocalDev with 'go run')
 * - Idempotent install: same content → 0 (Go: TestInstallHooks_Idempotent)
 * - Force reinstall: forces rewrite → 1 (Go: TestInstallHooks_ForceReinstall)
 * - Rewrite when content differs: localDev → production switch → 1 (Go:
 *   TestInstallHooks_RewritesWhenContentDiffers)
 * - Uninstall: removes file (Go: TestUninstallHooks)
 * - Uninstall when missing: no error (Go: TestUninstallHooks_NoFile)
 * - areHooksInstalled true after install / false after uninstall (Go:
 *   TestAreHooksInstalled)
 */

import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { OpenCodeAgent } from '@/agent/opencode';
import { areHooksInstalled, installHooks, uninstallHooks } from '@/agent/opencode/hooks';
import * as paths from '@/paths';

let tmpDir: string;
let originalCwd: string;

beforeEach(async () => {
	tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'opencode-hooks-'));
	originalCwd = process.cwd();
	// Init minimal git repo so worktreeRoot resolves.
	await fs.mkdir(path.join(tmpDir, '.git'));
	await fs.writeFile(path.join(tmpDir, '.git', 'HEAD'), 'ref: refs/heads/main\n');
	process.chdir(tmpDir);
});

afterEach(async () => {
	process.chdir(originalCwd);
	await fs.rm(tmpDir, { recursive: true, force: true });
});

describe('agent/opencode/hooks — Go: hooks.go + hooks_test.go', () => {
	describe('installHooks — fresh install (production)', () => {
		// Go: TestInstallHooks_FreshInstall (hooks_test.go:18-53)
		it('writes plugin file to .opencode/plugins/story.ts → 1', async () => {
			const count = await installHooks({ localDev: false, force: false });
			expect(count).toBe(1);
			const pluginPath = path.join(tmpDir, '.opencode', 'plugins', 'story.ts');
			const content = await fs.readFile(pluginPath, 'utf-8');
			// Story rebrand: production CMD literal
			expect(content).toContain("const STORY_CMD = 'story'");
			expect(content).toContain('hooks opencode');
			expect(content).toContain('StoryPlugin');
			// Production install must NOT have 'bun run' / 'go run'
			expect(content).not.toContain('bun run');
			expect(content).not.toContain('go run');
		});
	});

	describe('installHooks — localDev', () => {
		// Go: TestInstallHooks_LocalDev (hooks_test.go:79-102) (with 'go run')
		// Story rebrand: 'bun run "$(git rev-parse --show-toplevel)"/src/cli.ts'
		it('localDev = true: plugin contains "bun run ... src/cli.ts"', async () => {
			const count = await installHooks({ localDev: true, force: false });
			expect(count).toBe(1);
			const pluginPath = path.join(tmpDir, '.opencode', 'plugins', 'story.ts');
			const content = await fs.readFile(pluginPath, 'utf-8');
			expect(content).toContain('bun run "$(git rev-parse --show-toplevel)"/src/cli.ts');
			expect(content).not.toContain("const STORY_CMD = 'story'");
		});
	});

	describe('installHooks — idempotency', () => {
		// Go: TestInstallHooks_Idempotent (hooks_test.go:55-77)
		it('same content twice: second install → 0', async () => {
			const count1 = await installHooks({ localDev: false, force: false });
			expect(count1).toBe(1);
			const count2 = await installHooks({ localDev: false, force: false });
			expect(count2).toBe(0);
		});

		// Go: TestInstallHooks_ForceReinstall (hooks_test.go:146-164)
		it('force = true: even with same content → 1 (rewrite)', async () => {
			await installHooks({ localDev: false, force: false });
			const count = await installHooks({ localDev: false, force: true });
			expect(count).toBe(1);
		});

		// Go: TestInstallHooks_RewritesWhenContentDiffers (hooks_test.go:166-208)
		it('content differs (localDev → production): rewrite → 1', async () => {
			const count1 = await installHooks({ localDev: true, force: false });
			expect(count1).toBe(1);
			const pluginPath = path.join(tmpDir, '.opencode', 'plugins', 'story.ts');
			const before = await fs.readFile(pluginPath, 'utf-8');
			expect(before).toContain('bun run');

			const count2 = await installHooks({ localDev: false, force: false });
			expect(count2).toBe(1);
			const after = await fs.readFile(pluginPath, 'utf-8');
			expect(after).not.toContain('bun run');
			expect(after).toContain("const STORY_CMD = 'story'");
		});
	});

	describe('uninstallHooks', () => {
		// Go: TestUninstallHooks (hooks_test.go:210-227)
		it('removes installed plugin file', async () => {
			await installHooks({ localDev: false, force: false });
			await uninstallHooks();
			const pluginPath = path.join(tmpDir, '.opencode', 'plugins', 'story.ts');
			await expect(fs.stat(pluginPath)).rejects.toMatchObject({ code: 'ENOENT' });
		});

		// Go: TestUninstallHooks_NoFile (hooks_test.go:229-238)
		it('no-op when plugin file missing (does not throw)', async () => {
			await expect(uninstallHooks()).resolves.toBeUndefined();
		});
	});

	describe('areHooksInstalled', () => {
		// Go: TestAreHooksInstalled (hooks_test.go:240-264)
		it('false → install → true → uninstall → false', async () => {
			expect(await areHooksInstalled()).toBe(false);
			await installHooks({ localDev: false, force: false });
			expect(await areHooksInstalled()).toBe(true);
			await uninstallHooks();
			expect(await areHooksInstalled()).toBe(false);
		});

		// Failure path: file exists but lacks Story marker → false
		it('plugin file without Story marker → false', async () => {
			const pluginDir = path.join(tmpDir, '.opencode', 'plugins');
			await fs.mkdir(pluginDir, { recursive: true });
			await fs.writeFile(path.join(pluginDir, 'story.ts'), '// not a Story plugin');
			expect(await areHooksInstalled()).toBe(false);
		});
	});

	describe('OpenCodeAgent class delegation', () => {
		// Verify the agent class wires through to module-level functions.
		it('agent.installHooks → file written', async () => {
			const a = new OpenCodeAgent();
			const count = await a.installHooks({ localDev: false, force: false });
			expect(count).toBe(1);
			expect(await a.areHooksInstalled()).toBe(true);
			await a.uninstallHooks();
			expect(await a.areHooksInstalled()).toBe(false);
		});
	});

	describe('error paths + cwd fallback', () => {
		it('installHooks still writes under cwd when worktreeRoot() fails', async () => {
			const spy = vi
				.spyOn(paths, 'worktreeRoot')
				.mockRejectedValueOnce(new Error('not a git repo'));
			const count = await installHooks({ localDev: false, force: false });
			expect(count).toBe(1);
			const pluginPath = path.join(tmpDir, '.opencode', 'plugins', 'story.ts');
			const content = await fs.readFile(pluginPath, 'utf-8');
			expect(content).toContain('Auto-generated by `story enable --agent opencode`');
			spy.mockRestore();
		});

		it('uninstallHooks throws when unlink fails with non-ENOENT', async () => {
			await installHooks({ localDev: false, force: false });
			const spy = vi
				.spyOn(fs, 'unlink')
				.mockRejectedValueOnce(Object.assign(new Error('permission denied'), { code: 'EACCES' }));
			await expect(uninstallHooks()).rejects.toThrow('failed to remove plugin file');
			spy.mockRestore();
		});

		it('areHooksInstalled returns false when readFile throws', async () => {
			await installHooks({ localDev: false, force: false });
			const spy = vi.spyOn(fs, 'readFile').mockRejectedValueOnce(new Error('boom'));
			expect(await areHooksInstalled()).toBe(false);
			spy.mockRestore();
		});

		it('installHooks still writes when readFile fails before write (treats as missing)', async () => {
			const pluginDir = path.join(tmpDir, '.opencode', 'plugins');
			await fs.mkdir(pluginDir, { recursive: true });
			const pluginPath = path.join(pluginDir, 'story.ts');
			await fs.writeFile(pluginPath, 'stale');
			const spy = vi.spyOn(fs, 'readFile').mockRejectedValueOnce(new Error('boom'));
			const count = await installHooks({ localDev: false, force: false });
			expect(count).toBe(1);
			const content = await fs.readFile(pluginPath, 'utf-8');
			expect(content).toContain("const STORY_CMD = 'story'");
			spy.mockRestore();
		});
	});
});
