/**
 * Tests for `src/agent/opencode/plugin-template.ts` — Mirrors Go
 * `entire-cli/cmd/entire/cli/agent/opencode/entire_plugin.ts` (embedded TS
 * source piped through Go `//go:embed`).
 *
 * **Story-side rebrand checklist** (Go → Story):
 * - File comment header: `entire enable --agent opencode` → `story enable --agent opencode`
 * - Symbol name: `EntirePlugin` → `StoryPlugin`
 * - In-template constant: `ENTIRE_CMD` → `STORY_CMD`
 * - Placeholder: `__ENTIRE_CMD__` → `__STORY_CMD__`
 * - Production guard: `command -v entire` → `command -v story`
 * - Hook subcommand prefix: `entire hooks opencode` → `story hooks opencode`
 *
 * Covers:
 * - PLUGIN_TEMPLATE has the Story-rebranded marker comment
 * - PLUGIN_TEMPLATE references `__STORY_CMD__` placeholder ≥ 1 time
 * - PLUGIN_TEMPLATE exports `StoryPlugin` (not `EntirePlugin`)
 * - PLUGIN_TEMPLATE includes 6 OpenCode event handlers
 * - PLUGIN_TEMPLATE uses `spawnSync` from `node:child_process` for
 *   turn-end / session-end (Go nuance — Bun compat)
 * - PLUGIN_TEMPLATE has the session-start guard (currentSessionID switch check)
 */

import { describe, expect, it } from 'vitest';
import { PLUGIN_TEMPLATE, STORY_CMD_PLACEHOLDER } from '@/agent/opencode/plugin-template';

describe('agent/opencode/plugin-template — Go: entire_plugin.ts', () => {
	// Story rebrand: header marker
	it('contains Story-rebranded marker comment', () => {
		expect(PLUGIN_TEMPLATE).toContain('Auto-generated by `story enable --agent opencode`');
	});

	// Story rebrand: placeholder constant
	it('STORY_CMD_PLACEHOLDER is "__STORY_CMD__"', () => {
		expect(STORY_CMD_PLACEHOLDER).toBe('__STORY_CMD__');
	});

	// Story rebrand: placeholder appears in template
	it('PLUGIN_TEMPLATE references __STORY_CMD__ placeholder', () => {
		expect(PLUGIN_TEMPLATE).toContain('__STORY_CMD__');
	});

	// Story rebrand: NO references to entire-anything (string literals)
	it('does NOT contain entire-prefixed literals (Story rebrand complete)', () => {
		expect(PLUGIN_TEMPLATE).not.toContain('EntirePlugin');
		expect(PLUGIN_TEMPLATE).not.toContain('__ENTIRE_CMD__');
		expect(PLUGIN_TEMPLATE).not.toContain('entire hooks opencode');
		expect(PLUGIN_TEMPLATE).not.toContain('command -v entire');
	});

	// Story rebrand: exports StoryPlugin
	it('exports StoryPlugin (not EntirePlugin)', () => {
		expect(PLUGIN_TEMPLATE).toContain('StoryPlugin');
	});

	// Story rebrand: production guard uses 'story'
	it('production guard checks for `command -v story`', () => {
		expect(PLUGIN_TEMPLATE).toContain('command -v story');
		expect(PLUGIN_TEMPLATE).toContain('exec story hooks opencode');
	});

	// Go: 6 event types handled
	it('handles all 6 OpenCode event types', () => {
		const eventTypes = [
			'session.created',
			'message.updated',
			'message.part.updated',
			'session.status',
			'session.compacted',
			'session.deleted',
			'server.instance.disposed',
		];
		for (const t of eventTypes) {
			expect(PLUGIN_TEMPLATE).toContain(t);
		}
	});

	// Go: lifecycle.go uses spawnSync for turn-end + session-end
	it('uses node:child_process spawnSync for turn-end (sync, opencode run exits on idle)', () => {
		expect(PLUGIN_TEMPLATE).toContain('spawnSync');
		expect(PLUGIN_TEMPLATE).toContain('"node:child_process"');
		// sync handler must be defined in template
		expect(PLUGIN_TEMPLATE).toContain('callHookSync');
	});

	// Bun.spawn / Bun.spawnSync must NOT appear (Story uses Node-compat APIs)
	it('does not reference Bun.spawn or Bun.spawnSync anywhere', () => {
		expect(PLUGIN_TEMPLATE).not.toContain('Bun.spawn');
		expect(PLUGIN_TEMPLATE).not.toContain('Bun.spawnSync');
	});

	// Go: hooks_test.go:104-144 (session-start guarded by currentSessionID switch)
	it('session-start is guarded by currentSessionID switch check', () => {
		const guardIdx = PLUGIN_TEMPLATE.indexOf('if (currentSessionID !== session.id)');
		expect(guardIdx).toBeGreaterThan(-1);
		const hookIdx = PLUGIN_TEMPLATE.indexOf('hookCmd("session-start")');
		expect(hookIdx).toBeGreaterThan(-1);
		const assignIdx = PLUGIN_TEMPLATE.indexOf('currentSessionID = session.id');
		expect(assignIdx).toBeGreaterThan(-1);
		expect(guardIdx).toBeLessThan(hookIdx);
		expect(hookIdx).toBeLessThan(assignIdx);
	});

	// Failure path: snapshot-style guard against silent regression
	// (any change to template structure should require explicit test update)
	it('template length is within expected range (smoke regression check)', () => {
		expect(PLUGIN_TEMPLATE.length).toBeGreaterThan(2000);
		expect(PLUGIN_TEMPLATE.length).toBeLessThan(15000);
	});
});
