/**
 * OpenCode plugin install / uninstall / detection.
 *
 * Mirrors Go `entire-cli/cmd/entire/cli/agent/opencode/hooks.go` +
 * `plugin.go`. Story rebrand:
 * - Plugin file name: `entire.ts` → `story.ts`
 * - Plugin marker: `Auto-generated by \`entire enable...\`` → `\`story enable...\``
 * - Production CMD: `'entire'` → `'story'`
 * - LocalDev CMD: `go run "$(git rev-parse --show-toplevel)"/cmd/entire/main.go`
 *   → `bun run "$(git rev-parse --show-toplevel)"/src/cli.ts`
 *
 * @packageDocumentation
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import { worktreeRoot } from '@/paths';
import { PLUGIN_TEMPLATE, STORY_CMD_PLACEHOLDER } from './plugin-template';

/** Plugin file name written under `.opencode/plugins/`. Mirrors Go
 *  `pluginFileName = "entire.ts"` (Story rebrand: `entire.ts → story.ts`). */
const PLUGIN_FILE_NAME = 'story.ts';
/** Subdirectory under `.opencode/` where plugins live (matches OpenCode upstream). */
const PLUGIN_DIR_NAME = 'plugins';
/** Marker comment inside the plugin file used by {@link areHooksInstalled} to
 *  detect Story-generated plugins. Mirrors Go `entireMarker` (Story rebrand). */
const STORY_MARKER = 'Auto-generated by `story enable --agent opencode`';

/** Production command literal injected into the plugin template at install time. */
const PRODUCTION_CMD = 'story';
/** LocalDev command literal injected into the plugin template at install time.
 *  Replaces Go's `go run "$(git rev-parse --show-toplevel)"/cmd/entire/main.go`
 *  with the Bun + TypeScript equivalent. */
const LOCALDEV_CMD = 'bun run "$(git rev-parse --show-toplevel)"/src/cli.ts';

/**
 * Compute the absolute path to the OpenCode plugin file:
 * `<worktreeRoot>/.opencode/plugins/story.ts`.
 *
 * Falls back to CWD if `worktreeRoot()` fails (matches Go: `os.Getwd()` fallback
 * when not in a git repo, useful for tests).
 *
 * Mirrors Go `getPluginPath`.
 */
async function getPluginPath(): Promise<string> {
	let repoRoot: string;
	try {
		repoRoot = await worktreeRoot();
	} catch {
		repoRoot = process.cwd();
	}
	return path.join(repoRoot, '.opencode', PLUGIN_DIR_NAME, PLUGIN_FILE_NAME);
}

/** Render the plugin template with the appropriate command prefix substituted. */
function renderTemplate(localDev: boolean): string {
	const cmd = localDev ? LOCALDEV_CMD : PRODUCTION_CMD;
	return PLUGIN_TEMPLATE.split(STORY_CMD_PLACEHOLDER).join(cmd);
}

/**
 * Install the OpenCode plugin to `<repoRoot>/.opencode/plugins/story.ts`.
 *
 * **Idempotent**: if the file already exists with identical content, returns
 * `0` without rewriting. With `force: true`, always rewrites and returns `1`.
 * If content differs (e.g., production vs localDev), rewrites and returns `1`.
 *
 * Returns the number of plugin files written (`0` or `1`).
 *
 * Mirrors Go `OpenCodeAgent.InstallHooks`.
 *
 * @example
 * await installHooks({ localDev: false, force: false });
 * // returns: 1 (fresh install)
 *
 * await installHooks({ localDev: false, force: false });
 * // returns: 0 (idempotent — same content)
 *
 * await installHooks({ localDev: true, force: false });
 * // returns: 1 (content differs — rewrite)
 *
 * // Side effects:
 * //   <repoRoot>/.opencode/plugins/        ← created (mode 0o755 default)
 * //   <repoRoot>/.opencode/plugins/story.ts ← written (mode 0o644 default)
 */
export async function installHooks(opts: { localDev: boolean; force: boolean }): Promise<number> {
	const pluginPath = await getPluginPath();
	const content = renderTemplate(opts.localDev);

	if (!opts.force) {
		try {
			const existing = await fs.readFile(pluginPath, 'utf-8');
			if (existing === content) {
				return 0;
			}
		} catch {
			// file missing — fall through to write
		}
	}

	await fs.mkdir(path.dirname(pluginPath), { recursive: true });
	await fs.writeFile(pluginPath, content);
	return 1;
}

/**
 * Remove the OpenCode plugin file. No-op (no throw) when the file is missing.
 *
 * Mirrors Go `OpenCodeAgent.UninstallHooks`.
 */
export async function uninstallHooks(): Promise<void> {
	const pluginPath = await getPluginPath();
	try {
		await fs.unlink(pluginPath);
	} catch (err) {
		if ((err as NodeJS.ErrnoException).code === 'ENOENT') {
			return;
		}
		throw new Error(`failed to remove plugin file: ${(err as Error).message}`, {
			cause: err as Error,
		});
	}
}

/**
 * Whether the Story OpenCode plugin is installed (file exists AND contains
 * the {@link STORY_MARKER} comment).
 *
 * Returns `false` for any error (missing file / unreadable / lacks marker).
 *
 * Mirrors Go `OpenCodeAgent.AreHooksInstalled`.
 */
export async function areHooksInstalled(): Promise<boolean> {
	const pluginPath = await getPluginPath();
	let data: string;
	try {
		data = await fs.readFile(pluginPath, 'utf-8');
	} catch {
		return false;
	}
	return data.includes(STORY_MARKER);
}
