/**
 * Embedded OpenCode plugin source — written verbatim into
 * `<repoRoot>/.opencode/plugins/story.ts` by `./hooks.ts: installHooks()`.
 *
 * Mirrors Go `entire-cli/cmd/entire/cli/agent/opencode/entire_plugin.ts`
 * (loaded via `//go:embed`). Story-side rebrands (5 literals — see plan
 * §"Story-side 偏离速查"):
 * - File comment: `entire enable --agent opencode` → `story enable --agent opencode`
 * - Symbol: `EntirePlugin` → `StoryPlugin`
 * - In-template constant: `ENTIRE_CMD` → `STORY_CMD`
 * - Placeholder: `__ENTIRE_CMD__` → {@link STORY_CMD_PLACEHOLDER}
 * - Production guard: `command -v entire` / `entire hooks opencode` →
 *   `command -v story` / `story hooks opencode`
 *
 * The placeholder is replaced at install time with either the production
 * `'story'` literal or the localDev `bun run "$(git rev-parse --show-toplevel)"/src/cli.ts`
 * shell expression.
 *
 * @packageDocumentation
 */

/**
 * Token in {@link PLUGIN_TEMPLATE} replaced by `installHooks()` with the
 * actual command prefix. Mirrors Go `entireCmdPlaceholder = "__ENTIRE_CMD__"`.
 */
export const STORY_CMD_PLACEHOLDER = '__STORY_CMD__' as const;

/**
 * Embedded TS source for the OpenCode plugin (Bun-runtime ESM module).
 *
 * **Why embedded as a string** (Story takes a different path from Go's
 * `//go:embed`): bundling this as a `.ts` file would require Bun loaders
 * to handle it differently from the rest of the source tree. A `const`
 * string in the same module the agent code lives in keeps the dependency
 * graph trivial.
 *
 * **Behavior** (Go-aligned, line-by-line):
 * - Imports `Plugin` type from `@opencode-ai/plugin`.
 * - Tracks per-session state: `seenUserMessages` Set, `currentSessionID`,
 *   `currentModel`, `messageStore` Map.
 * - `hookCmd(name)`: builds shell argv. LocalDev passes through
 *   `${STORY_CMD} hooks opencode <name>`; production wraps in
 *   `command -v story` guard so missing-binary case exits silently.
 * - `callHook(name, payload)`: async; pipes JSON to subprocess; swallows
 *   all errors (plugin must NEVER crash OpenCode).
 * - `callHookSync(name, payload)`: sync (`node:child_process.spawnSync`);
 *   used for `turn-end` / `session-end` / `server.instance.disposed`
 *   because `opencode run` exits on the same idle event that triggers
 *   turn-end — async would be killed before completing.
 * - 6 event types handled: `session.created` / `message.updated` /
 *   `message.part.updated` / `session.status` (idle) / `session.compacted`
 *   / `session.deleted` / `server.instance.disposed`.
 *
 * Story-rebrand note: the plugin file written to disk is named `story.ts`
 * (Go: `entire.ts`); the marker comment changes to `story enable --agent
 * opencode`.
 */
export const PLUGIN_TEMPLATE = `// Story CLI plugin for OpenCode
// Auto-generated by \`story enable --agent opencode\`
// Do not edit manually — changes will be overwritten on next install.
// Loaded by OpenCode's Bun-based plugin system; uses node:child_process
// (Bun ships a Node-compatible API so either runtime works).
import { spawn, spawnSync } from "node:child_process"
import type { Plugin } from "@opencode-ai/plugin"

export const StoryPlugin: Plugin = async ({ directory }) => {
  const STORY_CMD = '${STORY_CMD_PLACEHOLDER}'
  // Track seen user messages to fire turn-start only once per message
  const seenUserMessages = new Set<string>()
  // Track current session ID for message events (which don't include sessionID)
  let currentSessionID: string | null = null
  // Track the model used by the most recent assistant message
  let currentModel: string | null = null
  // In-memory store for message metadata (role, tokens, etc.)
  const messageStore = new Map<string, any>()

  /**
   * Build the shell command for a hook invocation.
   * Uses sh -c so that shell command substitution in STORY_CMD
   * (e.g., $(git rev-parse --show-toplevel) for local-dev) is interpreted.
   */
  function hookCmd(hookName: string): string[] {
    if (STORY_CMD !== "story") {
      return ["sh", "-c", \`\${STORY_CMD} hooks opencode \${hookName}\`]
    }
    return ["sh", "-c", \`if ! command -v story >/dev/null 2>&1; then exit 0; fi; exec story hooks opencode \${hookName}\`]
  }

  /**
   * Pipe JSON payload to a story hooks command (async).
   * Errors are logged but never thrown — plugin failures must not crash OpenCode.
   */
  async function callHook(hookName: string, payload: Record<string, unknown>) {
    try {
      const json = JSON.stringify(payload)
      const [cmd, ...rest] = hookCmd(hookName)
      const child = spawn(cmd, rest, {
        cwd: directory,
        stdio: ["pipe", "ignore", "ignore"],
      })
      child.stdin?.end(json + "\\n")
      await new Promise<void>((resolve) => {
        child.once("error", () => resolve())
        child.once("exit", () => resolve())
      })
    } catch {
      // Silently ignore — plugin failures must not crash OpenCode
    }
  }

  /**
   * Synchronous variant for hooks that fire near process exit (turn-end, session-end).
   * \`opencode run\` breaks its event loop on the same session.status idle event that
   * triggers turn-end. The async callHook would be killed before completing.
   * spawnSync blocks the event loop, preventing exit until the hook finishes.
   */
  function callHookSync(hookName: string, payload: Record<string, unknown>) {
    try {
      const json = JSON.stringify(payload)
      const [cmd, ...rest] = hookCmd(hookName)
      spawnSync(cmd, rest, {
        cwd: directory,
        input: json + "\\n",
        stdio: ["pipe", "ignore", "ignore"],
      })
    } catch {
      // Silently ignore — plugin failures must not crash OpenCode
    }
  }

  return {
    event: async ({ event }) => {
      try {
        switch (event.type) {
          case "session.created": {
            const session = (event as any).properties?.info
            if (!session?.id) break
            // Reset per-session tracking state when switching sessions.
            if (currentSessionID !== session.id) {
              seenUserMessages.clear()
              messageStore.clear()
              currentModel = null
              const json = JSON.stringify({
                session_id: session.id,
              })
              const [cmd, ...rest] = hookCmd("session-start")
              const child = spawn(cmd, rest, {
                cwd: directory,
                stdio: ["pipe", "ignore", "ignore"],
              })
              child.stdin?.end(json + "\\n")
              await new Promise<void>((resolve) => {
                child.once("error", () => resolve())
                child.once("exit", () => resolve())
              })
            }
            currentSessionID = session.id
            break
          }

          case "message.updated": {
            const msg = (event as any).properties?.info
            if (!msg) break
            // Store message metadata (role, time, tokens, etc.)
            messageStore.set(msg.id, msg)
            // Track model from assistant messages
            if (msg.role === "assistant" && msg.modelID) {
              currentModel = msg.modelID
            }
            break
          }

          case "message.part.updated": {
            const part = (event as any).properties?.part
            if (!part?.messageID) break

            // Fire turn-start on the first text part of a new user message
            const msg = messageStore.get(part.messageID)
            if (msg?.role === "user" && part.type === "text" && !seenUserMessages.has(msg.id)) {
              seenUserMessages.add(msg.id)
              const sessionID = msg.sessionID ?? currentSessionID
              if (sessionID) {
                await callHook("turn-start", {
                  session_id: sessionID,
                  prompt: part.text ?? "",
                  model: currentModel ?? "",
                })
              }
            }
            break
          }

          case "session.status": {
            // session.status fires in both TUI and non-interactive (run) mode.
            // session.idle is deprecated and not reliably emitted in run mode.
            const props = (event as any).properties
            if (props?.status?.type !== "idle") break
            const sessionID = props?.sessionID ?? currentSessionID
            if (!sessionID) break
            // Use sync variant: \`opencode run\` exits on the same idle event,
            // so an async hook would be killed before completing.
            callHookSync("turn-end", {
              session_id: sessionID,
              model: currentModel ?? "",
            })
            break
          }

          case "session.compacted": {
            const sessionID = (event as any).properties?.sessionID
            if (!sessionID) break
            await callHook("compaction", {
              session_id: sessionID,
            })
            break
          }

          case "session.deleted": {
            const session = (event as any).properties?.info
            if (!session?.id) break
            seenUserMessages.clear()
            messageStore.clear()
            currentSessionID = null
            // Use sync variant: session-end may fire during shutdown.
            callHookSync("session-end", {
              session_id: session.id,
            })
            break
          }

          case "server.instance.disposed": {
            // Fires when OpenCode shuts down (TUI close or \`opencode run\` exit).
            // session.deleted only fires on explicit user deletion, not on quit,
            // so this is the only reliable way to end sessions on exit.
            if (!currentSessionID) break
            const sessionID = currentSessionID
            seenUserMessages.clear()
            messageStore.clear()
            currentSessionID = null
            // Use sync variant: this is the last event before process exit.
            callHookSync("session-end", {
              session_id: sessionID,
            })
            break
          }
        }
      } catch {
        // Silently ignore — plugin failures must not crash OpenCode
      }
    },
  }
}
`;
