import { describe, expect, it } from 'vitest';
import { stripIDEContextTags } from '@/textutil';

describe('stripIDEContextTags', () => {
	it('strips ide_opened_file blocks', () => {
		const input = 'before<ide_opened_file path="x">content</ide_opened_file>after';
		expect(stripIDEContextTags(input)).toBe('beforeafter');
	});

	it('strips ide_selection blocks', () => {
		const input = '<ide_selection>selected</ide_selection>text';
		expect(stripIDEContextTags(input)).toBe('text');
	});

	it('strips system-reminder', () => {
		const input = 'before<system-reminder>...</system-reminder>after';
		expect(stripIDEContextTags(input)).toBe('beforeafter');
	});

	it('strips user_query tags', () => {
		const input = '<user_query>question</user_query>';
		expect(stripIDEContextTags(input)).toBe('question');
	});

	it('strips command-name', () => {
		const input = '<command-name>cmd</command-name>';
		expect(stripIDEContextTags(input)).toBe('');
	});

	it('strips local-command-stdout', () => {
		const input = '<local-command-stdout>output</local-command-stdout>';
		expect(stripIDEContextTags(input)).toBe('');
	});

	it('no-op for plain text', () => {
		expect(stripIDEContextTags('plain text')).toBe('plain text');
	});

	it('handles empty string', () => {
		expect(stripIDEContextTags('')).toBe('');
	});

	it('strips nested content', () => {
		const input = '<ide_opened_file path="x"><b>rich</b></ide_opened_file>';
		expect(stripIDEContextTags(input)).toBe('');
	});

	it('strips multiple tags', () => {
		const input = 'text<system-reminder>r</system-reminder>middle<user_query>q</user_query>end';
		expect(stripIDEContextTags(input)).toBe('textmiddleqend');
	});

	it('strips multiline ide_selection', () => {
		const input =
			'<ide_selection>func main() {\n    fmt.Println("hello")\n}</ide_selection>\n\noptimize this';
		expect(stripIDEContextTags(input)).toBe('optimize this');
	});

	it('strips ide_cursor_position (unknown future ide tag)', () => {
		const input =
			'<ide_cursor_position line="42" col="10">cursor info</ide_cursor_position>\n\nhelp me here';
		expect(stripIDEContextTags(input)).toBe('help me here');
	});

	it('preserves other XML-like content (user_note, system)', () => {
		const input = '<user_note>important</user_note> and <system>info</system>';
		expect(stripIDEContextTags(input)).toBe(
			'<user_note>important</user_note> and <system>info</system>',
		);
	});

	it('strips local-command-caveat', () => {
		const input =
			'<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>my actual prompt';
		expect(stripIDEContextTags(input)).toBe('my actual prompt');
	});

	it('whitespace-only after stripping returns empty', () => {
		const input = '<ide_opened_file>file.md</ide_opened_file>   \n\n   ';
		expect(stripIDEContextTags(input)).toBe('');
	});
});
